os: unstable

environment:
    doBlink1Control: false
#

platform:
- x86
- x64

install:
- ps: $env:Path = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\vc\bin;" + $env:Path
- ps: if ( $env:Platform -eq "x64" ) {
       $env:Path = "C:\msys64\mingw64\bin;C:\msys64\usr\bin;" + $env:Path
     } else {
       $env:Path = "C:\msys64\mingw32\bin;C:\msys64\usr\bin;" + $env:Path
     }
# add zip command for scripts later
- ps: pacman -S zip unzip --noconfirm
- ps: env
# 'which git' in powershell
- ps: get-command git

build_script:
- ps: cd commandline
- ps: make CC=gcc package
- ps: make CC=gcc package-tiny-server

# NOTE: blink1control-tool takes a while to build because of curl, for CI dev, set doBlink1Control=false
- ps: if ( $env:doBlink1Control -eq "true" ) {
      cd blink1control-tool ;
      make json-parser-setup ;
      make curl-setup ;
      make CC=gcc package
    }

artifacts:
    - path: 'commandline\blink1-tool*.zip'
      name: blink1-tool
    - path: 'commandline\blink1-lib*.zip'
      name: blink1-lib
    - path: 'commandline\blink1-tiny-server*.zip'
      name: blink1-tiny-server
    - path: 'commandline\blink1control-tool\blink1control-tool*.zip'
      name: blink1control-tool

deploy:
  provider: S3
  access_key_id:
      secure: k+MjsHqRpP9DkNI3S+8W5CedlW+P6MbL2I+s9UKfH2w=
  secret_access_key:
      secure: QiRehApfnik9m7tDFwssuTgeLlcGO3LrnJvL6apGxESPOtBt/8beI6ebxczBBB99
  bucket: todtravistest2
  folder: blink1
